---

# The workflow will generate the SBOM file for the repository
# and vulerability scan report for the SBOM file using CycloneDX
# The workflow will run on push to main branch and manually triggered workflows
# The results will be stored in the action artifacts

name: 'CDXGen'
on:
  workflow_dispatch:
    inputs:
      generate_cdx_report:
        description: "Generate CycloneDX report"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - 'main'
permissions:
  contents: read
jobs:
  cdxgen:
    runs-on: ubuntu-latest
    steps:
      - name: "cdxgen"
        uses: netcracker/qubership-workflow-hub/actions/cdxgen@v1.0.6
        with:
          generate_cdx_report: ${{ github.event.inputs.generate_cdx_report }}
  deploy-pages:
    if: ${{ github.event.inputs.generate_cdx_report }}
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: cdxgen
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      - name: "Summary"
        run: |
          echo "${{ steps.deployment.outputs.page_url }}cyclondx-report" >> $GITHUB_STEP_SUMMARY
