---

name: 'Dependency Review'
on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Get the first commit SHA"
        if: github.event_name == 'workflow_dispatch'
        id: first-commit
        run: echo "first_commit_sha=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
      - name: 'Dependency Review (manual)'
        if: github.event_name == 'workflow_dispatch'
        uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b # v4.7.3
        with:
          base-ref: ${{ env.first_commit_sha }}
          head-ref: ${{ github.ref }}
          show-openssf-scorecard: true
          vulnerability-check: true
          license-check: true
          warn-only: true
      - name: 'Dependency Review (pull_request)'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b # v4.7.3
        with:
          show-openssf-scorecard: true
          vulnerability-check: true
          license-check: true
