name: Dev Mvn Docker Build
run-name: "Dev build repository: ${{ github.ref_name }} #${{ github.run_number }}"

on:
  workflow_dispatch:
    inputs:
      maven-command:
        description: 'Maven command'
        required: false
        type: string
        default: "--batch-mode package -Dgpg.skip=true"
      artifact-name:
        description: 'Artifact name'
        required: false
        default: ''
      tags:
        description: 'Tags'
        required: false
        type: string
        default: ''
      java-version:
        description: 'Java version (e.g., 21)'
        required: false
        type: string
        default: "21"
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: false
permissions:
  contents: read

jobs:
  dev-build:
    permissions:
      contents: read
      packages: write
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@v1.0.6
    with:
      maven-command: "${{ github.event.inputs.maven-command }}"
      java-version: ${{ github.event.inputs.java-version }}
      upload-artifact: true
      artifact-id: ${{ github.event.inputs.artifact-name || github.event.repository.name }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}

  perform-version:
    runs-on: ubuntu-latest
    needs: dev-build
    outputs:
      metadata: "${{ steps.metadata.outputs.result }}"
      tags: "${{ steps.prepare_tags.outputs.tags }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Create name
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@v1.0.6
        id: metadata

      - name: Prepare tags
        id: prepare_tags
        run: |
          BASE_TAG="${{ steps.metadata.outputs.result }}"
          EXTRA_TAG="${{ github.event.inputs.tags }}"
          if [ -n "$EXTRA_TAG" ]; then
            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
          else
            TAGS="${BASE_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Summary step
        run: |
          echo "**Metadata:** ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** ${{ steps.prepare_tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

  docker-build:
    permissions:
      contents: read
      packages: write
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@v1.0.6
    needs: perform-version
    with:
      ref: ${{ github.event.ref }}
      artifact-id: ${{ github.event.inputs.artifact-name || github.event.repository.name }}
      dry-run: ${{ inputs.dry-run }}
      download-artifact: true
      tags: ${{ needs.perform-version.outputs.tags }}
