# This Docker Build and Publish GitHub Action automates the process of building and publishing Docker images using Docker Buildx.
# It supports multi-platform builds, custom tagging, and integration with GitHub Container Registry.
# See more details in the [GitHub Action documentation](https://github.com/netcracker/qubership-workflow-hub/blob/main/actions/docker-action/README.md)
# The workflow is triggered on pushes to the main branch and can also be manually triggered using `workflow_dispatch`.
# The workflow includes a job that checks out the repository, builds the Docker image, and publishes it to a specified registry.

name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      custom-image-name:
        description: 'Custom image name'
        required: false
        default: ''
      platforms:
        description: 'Platforms'
        required: false
        type: string
        default: ''
      tags:
        description: 'Tags'
        required: false
        type: string
        default: ''
      dry-run:
        description: 'Dry run'
        required: false
        type: boolean
        default: false
permissions:
  contents: read

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Build and Publish Docker Image
        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.6
        with:
          ref: main
          custom-image-name: my-custom-image
          platforms: linux/amd64,linux/arm64
          tags: latest, v1.0.0
          dry-run: false
          download-artifact: true
          download-artifact-path: ./artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
