---
name: Link Checker

on:
  push: null
  repository_dispatch: null
  workflow_dispatch: null
  pull_request:
    branches: [main]
  permissions:
    contents: read
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Restore lychee cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: restore-cache
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            './**/*.md'
            --verbose
            --no-progress
            --user-agent 'Mozilla/5.0 (X11; Linux x86_64) Chrome/134.0.0.0'
            --retry-wait-time 60
            --max-retries 8
            --accept 100..=103,200..=299,429
            --cookie-jar cookies.json
            --exclude-all-private
            --max-concurrency 4
            --cache
            --cache-exclude-status '429, 500..502'
            --max-cache-age 1d
          format: markdown
          fail: true
