name: Publish NPM package

run-name: NPM Package${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.dry-run)) && ' - Test' || ' - Publish' }}${{ (github.event_name == 'workflow_dispatch' && !inputs.dry-run && inputs.version) && format(' {0}', inputs.version) || '' }}

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version for NPM (e.g., 1.0.0)'
        required: false
        type: string
      scope:
        description: 'NPM scope for the package'
        required: false
        type: string
        default: '@netcracker'
      node-version:
        required: false
        type: string
        default: "22.x"
      registry-url:
        required: false
        type: string
        default: "https://npm.pkg.github.com"
      update-nc-dependency:
        required: false
        type: boolean
        default: false
      dry-run:
        description: 'Run in dry-run mode (no actual publishing)'
        required: false
        type: boolean
        default: false
      npm-dist-tag:
        description: 'NPM distribution tag'
        required: false
        type: string
        default: 'latest'

permissions:
  contents: write
  packages: write

jobs:
  npm-publish:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/re-npm-publish.yml@main
    with:
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || '' }}
      scope: ${{ github.event_name == 'workflow_dispatch' && inputs.scope || '@netcracker' }}
      node-version: ${{ github.event_name == 'workflow_dispatch' && inputs.node-version || '22.x' }}
      registry-url: ${{ github.event_name == 'workflow_dispatch' && inputs.registry-url || 'https://npm.pkg.github.com' }}
      update-nc-dependency: ${{ github.event_name == 'workflow_dispatch' && inputs.update-nc-dependency || false }}
      dry-run: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.dry-run) }}
      dist-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.npm-dist-tag || 'latest' }}
      ref: ${{ github.ref_name }}
    secrets: inherit
