name: Docker Scout CVE Scan

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Public images (sample: nginx:1.27)"
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_RW_TOKEN }}

      - name: Run Docker Scout CVEs
        id: scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ inputs.image }}
          only-severities: critical,high
          only-fixed: false
          exit-code: true
          sarif-file: scout-results.sarif
